services:
- type: web
  region: frankfurt
  name: next-js
  env: node
  plan: starter
  buildCommand: yarn; yarn build
  startCommand: yarn start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production

- type: cron
  name: bridge-bot
  region: frankfurt
  plan: Starter
  env: node
  schedule: "*/5 * * * *"
  buildCommand: "node dist/bot.js"
  startCommand: date

databases:
  # DEV DB
  - name: dev-db
    region: frankfurt
    plan: Starter
  # PROD DB
  - name: prod-db
    region: frankfurt
    plan:
      Standard