services:
- type: web
  region: frankfurt
  name: bridge-server-dev
  env: node
  plan: starter
  buildCommand: yarn; yarn generate; yarn build; yarn seed; 
  startCommand: yarn start
  autoDeploy: true
  envVars:
  - key: NODE_ENV
    value: production

- type: cron
  name: bridge-bot-dev
  region: frankfurt
  plan: Starter
  env: node
  schedule: "1 * * * *"
  buildCommand: yarn; yarn build
  startCommand: yarn bot


databases:
  - name: bridge-db-dev
    region: frankfurt
    plan: Starter
  - name: bridge-db-local
    region: frankfurt
    plan:
      Standard