services:
- type: web
  region: frankfurt
  name: bridge-server-dev
  env: node
  plan: starter
  buildCommand: yarn; yarn build
  startCommand: yarn start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production

- type: cron
  name: bridge-bot-dev
  region: frankfurt
  plan: Starter
  env: node
  schedule: "*/5 * * * *"
  buildCommand: "node dist/bot.js"
  startCommand: date

databases:
  - name: bridge-db-dev
    region: frankfurt
    plan: Starter
  - name: bridge-db-local
    region: frankfurt
    plan:
      Standard