/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface EthereumDIDRegistryInterface extends utils.Interface {
  functions: {
    "addDelegate(address,bytes32,address,uint256)": FunctionFragment;
    "addDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address,uint256)": FunctionFragment;
    "addDelegateSigned(address,bytes,bytes32,address,uint256)": FunctionFragment;
    "changeOwner(address,address)": FunctionFragment;
    "changeOwnerSigned(address,uint8,bytes32,bytes32,address)": FunctionFragment;
    "changeOwnerSigned(address,bytes,address)": FunctionFragment;
    "changed(address)": FunctionFragment;
    "delegates(address,bytes32,address)": FunctionFragment;
    "identityOwner(address)": FunctionFragment;
    "nonce(address)": FunctionFragment;
    "owners(address)": FunctionFragment;
    "revokeAttribute(address,bytes32,bytes)": FunctionFragment;
    "revokeAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes)": FunctionFragment;
    "revokeAttributeSigned(address,bytes,bytes32,bytes)": FunctionFragment;
    "revokeDelegate(address,bytes32,address)": FunctionFragment;
    "revokeDelegateSigned(address,bytes,bytes32,address)": FunctionFragment;
    "revokeDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address)": FunctionFragment;
    "setAttribute(address,bytes32,bytes,uint256)": FunctionFragment;
    "setAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes,uint256)": FunctionFragment;
    "setAttributeSigned(address,bytes,bytes32,bytes,uint256)": FunctionFragment;
    "validDelegate(address,bytes32,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addDelegate"
      | "addDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address,uint256)"
      | "addDelegateSigned(address,bytes,bytes32,address,uint256)"
      | "changeOwner"
      | "changeOwnerSigned(address,uint8,bytes32,bytes32,address)"
      | "changeOwnerSigned(address,bytes,address)"
      | "changed"
      | "delegates"
      | "identityOwner"
      | "nonce"
      | "owners"
      | "revokeAttribute"
      | "revokeAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes)"
      | "revokeAttributeSigned(address,bytes,bytes32,bytes)"
      | "revokeDelegate"
      | "revokeDelegateSigned(address,bytes,bytes32,address)"
      | "revokeDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address)"
      | "setAttribute"
      | "setAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes,uint256)"
      | "setAttributeSigned(address,bytes,bytes32,bytes,uint256)"
      | "validDelegate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addDelegate",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addDelegateSigned(address,bytes,bytes32,address,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "changeOwner",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "changeOwnerSigned(address,uint8,bytes32,bytes32,address)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "changeOwnerSigned(address,bytes,address)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "changed",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "delegates",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "identityOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "nonce",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "owners",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAttribute",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAttributeSigned(address,bytes,bytes32,bytes)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegate",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegateSigned(address,bytes,bytes32,address)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttribute",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttributeSigned(address,bytes,bytes32,bytes,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validDelegate",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDelegateSigned(address,bytes,bytes32,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeOwnerSigned(address,uint8,bytes32,bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeOwnerSigned(address,bytes,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "changed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delegates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeAttribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAttributeSigned(address,bytes,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegateSigned(address,bytes,bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttributeSigned(address,bytes,bytes32,bytes,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validDelegate",
    data: BytesLike
  ): Result;

  events: {
    "DIDAttributeChanged(address,bytes32,bytes,uint256,uint256)": EventFragment;
    "DIDDelegateChanged(address,bytes32,address,uint256,uint256)": EventFragment;
    "DIDOwnerChanged(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DIDAttributeChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DIDDelegateChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DIDOwnerChanged"): EventFragment;
}

export interface DIDAttributeChangedEventObject {
  identity: string;
  name: string;
  value: string;
  validTo: BigNumber;
  previousChange: BigNumber;
}
export type DIDAttributeChangedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  DIDAttributeChangedEventObject
>;

export type DIDAttributeChangedEventFilter =
  TypedEventFilter<DIDAttributeChangedEvent>;

export interface DIDDelegateChangedEventObject {
  identity: string;
  delegateType: string;
  delegate: string;
  validTo: BigNumber;
  previousChange: BigNumber;
}
export type DIDDelegateChangedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  DIDDelegateChangedEventObject
>;

export type DIDDelegateChangedEventFilter =
  TypedEventFilter<DIDDelegateChangedEvent>;

export interface DIDOwnerChangedEventObject {
  identity: string;
  owner: string;
  previousChange: BigNumber;
}
export type DIDOwnerChangedEvent = TypedEvent<
  [string, string, BigNumber],
  DIDOwnerChangedEventObject
>;

export type DIDOwnerChangedEventFilter = TypedEventFilter<DIDOwnerChangedEvent>;

export interface EthereumDIDRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EthereumDIDRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "addDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address,uint256)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "addDelegateSigned(address,bytes,bytes32,address,uint256)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changeOwner(
      identity: PromiseOrValue<string>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "changeOwnerSigned(address,uint8,bytes32,bytes32,address)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "changeOwnerSigned(address,bytes,address)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    delegates(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    identityOwner(
      identity: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    nonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    revokeAttribute(
      identity: PromiseOrValue<string>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "revokeAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "revokeAttributeSigned(address,bytes,bytes32,bytes)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "revokeDelegateSigned(address,bytes,bytes32,address)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "revokeDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAttribute(
      identity: PromiseOrValue<string>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "setAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes,uint256)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "setAttributeSigned(address,bytes,bytes32,bytes,uint256)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    validDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  addDelegate(
    identity: PromiseOrValue<string>,
    delegateType: PromiseOrValue<BytesLike>,
    delegate: PromiseOrValue<string>,
    validity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "addDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address,uint256)"(
    identity: PromiseOrValue<string>,
    sigV: PromiseOrValue<BigNumberish>,
    sigR: PromiseOrValue<BytesLike>,
    sigS: PromiseOrValue<BytesLike>,
    delegateType: PromiseOrValue<BytesLike>,
    delegate: PromiseOrValue<string>,
    validity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "addDelegateSigned(address,bytes,bytes32,address,uint256)"(
    identity: PromiseOrValue<string>,
    signature: PromiseOrValue<BytesLike>,
    delegateType: PromiseOrValue<BytesLike>,
    delegate: PromiseOrValue<string>,
    validity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changeOwner(
    identity: PromiseOrValue<string>,
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "changeOwnerSigned(address,uint8,bytes32,bytes32,address)"(
    identity: PromiseOrValue<string>,
    sigV: PromiseOrValue<BigNumberish>,
    sigR: PromiseOrValue<BytesLike>,
    sigS: PromiseOrValue<BytesLike>,
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "changeOwnerSigned(address,bytes,address)"(
    identity: PromiseOrValue<string>,
    signature: PromiseOrValue<BytesLike>,
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changed(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  delegates(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BytesLike>,
    arg2: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  identityOwner(
    identity: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  nonce(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owners(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  revokeAttribute(
    identity: PromiseOrValue<string>,
    name: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "revokeAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes)"(
    identity: PromiseOrValue<string>,
    sigV: PromiseOrValue<BigNumberish>,
    sigR: PromiseOrValue<BytesLike>,
    sigS: PromiseOrValue<BytesLike>,
    name: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "revokeAttributeSigned(address,bytes,bytes32,bytes)"(
    identity: PromiseOrValue<string>,
    signature: PromiseOrValue<BytesLike>,
    name: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeDelegate(
    identity: PromiseOrValue<string>,
    delegateType: PromiseOrValue<BytesLike>,
    delegate: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "revokeDelegateSigned(address,bytes,bytes32,address)"(
    identity: PromiseOrValue<string>,
    signature: PromiseOrValue<BytesLike>,
    delegateType: PromiseOrValue<BytesLike>,
    delegate: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "revokeDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address)"(
    identity: PromiseOrValue<string>,
    sigV: PromiseOrValue<BigNumberish>,
    sigR: PromiseOrValue<BytesLike>,
    sigS: PromiseOrValue<BytesLike>,
    delegateType: PromiseOrValue<BytesLike>,
    delegate: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAttribute(
    identity: PromiseOrValue<string>,
    name: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BytesLike>,
    validity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "setAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes,uint256)"(
    identity: PromiseOrValue<string>,
    sigV: PromiseOrValue<BigNumberish>,
    sigR: PromiseOrValue<BytesLike>,
    sigS: PromiseOrValue<BytesLike>,
    name: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BytesLike>,
    validity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "setAttributeSigned(address,bytes,bytes32,bytes,uint256)"(
    identity: PromiseOrValue<string>,
    signature: PromiseOrValue<BytesLike>,
    name: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BytesLike>,
    validity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  validDelegate(
    identity: PromiseOrValue<string>,
    delegateType: PromiseOrValue<BytesLike>,
    delegate: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    addDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "addDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address,uint256)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "addDelegateSigned(address,bytes,bytes32,address,uint256)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    changeOwner(
      identity: PromiseOrValue<string>,
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeOwnerSigned(address,uint8,bytes32,bytes32,address)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeOwnerSigned(address,bytes,address)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    changed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delegates(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    identityOwner(
      identity: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    nonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    revokeAttribute(
      identity: PromiseOrValue<string>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeAttributeSigned(address,bytes,bytes32,bytes)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeDelegateSigned(address,bytes,bytes32,address)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setAttribute(
      identity: PromiseOrValue<string>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes,uint256)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAttributeSigned(address,bytes,bytes32,bytes,uint256)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    validDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "DIDAttributeChanged(address,bytes32,bytes,uint256,uint256)"(
      identity?: PromiseOrValue<string> | null,
      name?: null,
      value?: null,
      validTo?: null,
      previousChange?: null
    ): DIDAttributeChangedEventFilter;
    DIDAttributeChanged(
      identity?: PromiseOrValue<string> | null,
      name?: null,
      value?: null,
      validTo?: null,
      previousChange?: null
    ): DIDAttributeChangedEventFilter;

    "DIDDelegateChanged(address,bytes32,address,uint256,uint256)"(
      identity?: PromiseOrValue<string> | null,
      delegateType?: null,
      delegate?: null,
      validTo?: null,
      previousChange?: null
    ): DIDDelegateChangedEventFilter;
    DIDDelegateChanged(
      identity?: PromiseOrValue<string> | null,
      delegateType?: null,
      delegate?: null,
      validTo?: null,
      previousChange?: null
    ): DIDDelegateChangedEventFilter;

    "DIDOwnerChanged(address,address,uint256)"(
      identity?: PromiseOrValue<string> | null,
      owner?: null,
      previousChange?: null
    ): DIDOwnerChangedEventFilter;
    DIDOwnerChanged(
      identity?: PromiseOrValue<string> | null,
      owner?: null,
      previousChange?: null
    ): DIDOwnerChangedEventFilter;
  };

  estimateGas: {
    addDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "addDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address,uint256)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "addDelegateSigned(address,bytes,bytes32,address,uint256)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changeOwner(
      identity: PromiseOrValue<string>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "changeOwnerSigned(address,uint8,bytes32,bytes32,address)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "changeOwnerSigned(address,bytes,address)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delegates(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    identityOwner(
      identity: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revokeAttribute(
      identity: PromiseOrValue<string>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "revokeAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "revokeAttributeSigned(address,bytes,bytes32,bytes)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "revokeDelegateSigned(address,bytes,bytes32,address)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "revokeDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAttribute(
      identity: PromiseOrValue<string>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "setAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes,uint256)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "setAttributeSigned(address,bytes,bytes32,bytes,uint256)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    validDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "addDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address,uint256)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "addDelegateSigned(address,bytes,bytes32,address,uint256)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changeOwner(
      identity: PromiseOrValue<string>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "changeOwnerSigned(address,uint8,bytes32,bytes32,address)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "changeOwnerSigned(address,bytes,address)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    delegates(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    identityOwner(
      identity: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revokeAttribute(
      identity: PromiseOrValue<string>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "revokeAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "revokeAttributeSigned(address,bytes,bytes32,bytes)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "revokeDelegateSigned(address,bytes,bytes32,address)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "revokeDelegateSigned(address,uint8,bytes32,bytes32,bytes32,address)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAttribute(
      identity: PromiseOrValue<string>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "setAttributeSigned(address,uint8,bytes32,bytes32,bytes32,bytes,uint256)"(
      identity: PromiseOrValue<string>,
      sigV: PromiseOrValue<BigNumberish>,
      sigR: PromiseOrValue<BytesLike>,
      sigS: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "setAttributeSigned(address,bytes,bytes32,bytes,uint256)"(
      identity: PromiseOrValue<string>,
      signature: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BytesLike>,
      validity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    validDelegate(
      identity: PromiseOrValue<string>,
      delegateType: PromiseOrValue<BytesLike>,
      delegate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
