/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc1271Sol from "./IERC1271.sol";
export type { ierc1271Sol };
export type { EthereumDIDRegistry } from "./EthereumDIDRegistry";
