/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ierc1271Sol from "./IERC1271.sol";
export { EthereumDIDRegistry__factory } from "./EthereumDIDRegistry__factory";
