/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cbTokenSol from "./CBToken.sol";
export type { cbTokenSol };
import type * as disperseWithDataSol from "./DisperseWithData.sol";
export type { disperseWithDataSol };
import type * as dids from "./dids";
export type { dids };
import type * as universalToken from "./universal-token";
export type { universalToken };
export type { Bridge } from "./Bridge";
export type { CBSToken } from "./CBSToken";
export type { ERC1400 } from "./ERC1400";
export type { TokenSwap } from "./TokenSwap";
export type { VCRegistry } from "./VCRegistry";
