/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC1400,
  IERC1400Interface,
} from "../../../contracts/DisperseWithData.sol/IERC1400";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "to",
        type: "address",
      },
      {
        name: "value",
        type: "uint256",
      },
      {
        name: "data",
        type: "bytes",
      },
    ],
    name: "transferWithData",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "from",
        type: "address",
      },
      {
        name: "to",
        type: "address",
      },
      {
        name: "value",
        type: "uint256",
      },
      {
        name: "data",
        type: "bytes",
      },
    ],
    name: "transferFromWithData",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC1400__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1400Interface {
    return new utils.Interface(_abi) as IERC1400Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1400 {
    return new Contract(address, _abi, signerOrProvider) as IERC1400;
  }
}
