/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CBToken__factory } from "./CBToken__factory";
export { VCRegistryInterface__factory } from "./VCRegistryInterface__factory";
