/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VCRegistryInterface,
  VCRegistryInterfaceInterface,
} from "../../../contracts/CBToken.sol/VCRegistryInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "bank",
        type: "address",
      },
    ],
    name: "authenticateBank",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "timeValid",
        type: "uint256",
      },
    ],
    name: "checkAuthenticated",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "checkAuthenticatedOnce",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "setAuthenticatedPerson",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class VCRegistryInterface__factory {
  static readonly abi = _abi;
  static createInterface(): VCRegistryInterfaceInterface {
    return new utils.Interface(_abi) as VCRegistryInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VCRegistryInterface {
    return new Contract(address, _abi, signerOrProvider) as VCRegistryInterface;
  }
}
